name: Test se-sshctl Formula

on:
  pull_request:
    paths:
      - se-sshctl.rb
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  test:
    runs-on: macos-26
    permissions:
      contents: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@fd832223f9f99ebf0244dd20658680e5d4aca049 # 2026.08.03.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: macos-26-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: macos-26-rubygems-

      - run: brew trust --formula ajchemist/tap/se-sshctl

      - run: brew style ajchemist/tap/se-sshctl

      - run: brew audit --strict ajchemist/tap/se-sshctl

      - run: brew install --formula --verbose ajchemist/tap/se-sshctl

      - run: brew test --verbose ajchemist/tap/se-sshctl
